project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - images/profile.png

website:
  title: "David Dubé"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: files/CV_DavidDube.pdf
        text: CV
        target: _blank  # Opens the CV in a new tab
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    execute:
      allow-html: true
editor: visual
